# CMake generated Testfile for 
# Source directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-functions/dune/functions/common/test
# Build directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-functions/dune/functions/common/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(differentiablefunctiontest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-functions/dune/functions/common/test/differentiablefunctiontest")
set_tests_properties(differentiablefunctiontest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-functions/dune/functions/common/test/differentiablefunctiontest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-functions/dune/functions/common/test/CMakeLists.txt;3;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-functions/dune/functions/common/test/CMakeLists.txt;0;")
add_test(polymorphicsmallobjecttest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-functions/dune/functions/common/test/polymorphicsmallobjecttest")
set_tests_properties(polymorphicsmallobjecttest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-functions/dune/functions/common/test/polymorphicsmallobjecttest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-functions/dune/functions/common/test/CMakeLists.txt;4;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-functions/dune/functions/common/test/CMakeLists.txt;0;")
