# CMake generated Testfile for 
# Source directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test
# Build directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(conformvolumevtktest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/conformvolumevtktest")
set_tests_properties(conformvolumevtktest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/conformvolumevtktest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;7;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(gnuplottest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/gnuplottest")
set_tests_properties(gnuplottest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/gnuplottest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;9;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(nonconformboundaryvtktest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/nonconformboundaryvtktest")
set_tests_properties(nonconformboundaryvtktest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/nonconformboundaryvtktest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;11;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(printgridtest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/printgridtest")
set_tests_properties(printgridtest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/printgridtest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;13;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(subsamplingvtktest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/subsamplingvtktest")
set_tests_properties(subsamplingvtktest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/subsamplingvtktest" SKIP_RETURN_CODE "77" TIMEOUT "600" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;15;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(vtktest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/vtktest")
set_tests_properties(vtktest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/vtktest" SKIP_RETURN_CODE "77" TIMEOUT "1200" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;19;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(vtktest-mpi-2 "/opt/homebrew/bin/mpiexec" "-n" "2" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/vtktest")
set_tests_properties(vtktest-mpi-2 PROPERTIES  LABELS "" PROCESSORS "2" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/vtktest" SKIP_RETURN_CODE "77" TIMEOUT "1200" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;19;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(vtksequencetest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/vtksequencetest")
set_tests_properties(vtksequencetest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/vtksequencetest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;23;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(amirameshtest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/amirameshtest")
set_tests_properties(amirameshtest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/amirameshtest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;25;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(starcdreadertest "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/starcdreadertest")
set_tests_properties(starcdreadertest PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/starcdreadertest" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;28;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(gmshtest-onedgrid "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/gmshtest-onedgrid")
set_tests_properties(gmshtest-onedgrid PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/gmshtest-onedgrid" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;33;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
add_test(gmshtest-uggrid "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/gmshtest-uggrid")
set_tests_properties(gmshtest-uggrid PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-grid/dune/grid/io/file/test/gmshtest-uggrid" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;39;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-grid/dune/grid/io/file/test/CMakeLists.txt;0;")
