# CMake generated Testfile for 
# Source directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes
# Build directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(recipe-geometry-grid "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-geometry-grid")
set_tests_properties(recipe-geometry-grid PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-geometry-grid" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;2;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-integrating-grid-functions "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-integrating-grid-functions")
set_tests_properties(recipe-integrating-grid-functions PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-integrating-grid-functions" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;3;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-grid-function-operations "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-grid-function-operations")
set_tests_properties(recipe-grid-function-operations PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-grid-function-operations" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;4;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-blocking "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-blocking")
set_tests_properties(recipe-blocking PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-blocking" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;5;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-linear-system-assembly "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-linear-system-assembly")
set_tests_properties(recipe-linear-system-assembly PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-linear-system-assembly" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;6;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-linear-system-solution-istl "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-linear-system-solution-istl")
set_tests_properties(recipe-linear-system-solution-istl PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-linear-system-solution-istl" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;7;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-linear-system-solution-pdelab "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-linear-system-solution-pdelab")
set_tests_properties(recipe-linear-system-solution-pdelab PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-linear-system-solution-pdelab" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;8;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-communication "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-communication")
set_tests_properties(recipe-communication PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-communication" SKIP_RETURN_CODE "77" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;9;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-operator-splitting "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-operator-splitting")
set_tests_properties(recipe-operator-splitting PROPERTIES  LABELS "" PROCESSORS "1" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-operator-splitting" SKIP_RETURN_CODE "77" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;10;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
add_test(recipe-operator-splitting-mpi-2 "/opt/homebrew/bin/mpiexec" "-n" "2" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-operator-splitting")
set_tests_properties(recipe-operator-splitting-mpi-2 PROPERTIES  LABELS "" PROCESSORS "2" REQUIRED_FILES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-pdelab/doc/Recipes/recipe-operator-splitting" SKIP_RETURN_CODE "77" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-common/cmake/modules/DuneTestMacros.cmake;397;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;10;dune_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-pdelab/doc/Recipes/CMakeLists.txt;0;")
