# CMake generated Testfile for 
# Source directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest
# Build directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(convergence_test_0000_0000 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_convergencetest.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/convergence_test_0000" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/0000.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(convergence_test_0000_0000 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;1;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;0;")
add_test(convergence_test_0000_0001 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_convergencetest.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/convergence_test_0000" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/0001.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(convergence_test_0000_0001 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;1;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;0;")
add_test(convergence_test_0001_0002 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_convergencetest.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/convergence_test_0001" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/0002.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(convergence_test_0001_0002 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;1;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;0;")
add_test(convergence_test_0001_0003 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_convergencetest.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/convergence_test_0001" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/0003.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(convergence_test_0001_0003 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;1;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;0;")
add_test(system_convergence_test_ "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_convergencetest.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/system_convergence_test" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/convergencetest/.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(system_convergence_test_ PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;8;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/convergencetest/CMakeLists.txt;0;")
