Python 2.7:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy sympy pexpect"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - maxima
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 2.7 Conda:
  script:
  - CONDA_ENVIRONMENT=.test-py2.yml
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
  - ". ./build-and-test-py-project-within-miniconda.sh"
  tags:
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3:
  script:
  - PY_EXE=python3
  - EXTRA_INSTALL="numpy sympy pexpect"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - maxima
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 Conda:
  script:
  - CONDA_ENVIRONMENT=.test-py3.yml
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
  - ". ./build-and-test-py-project-within-miniconda.sh"
  tags:
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 Conda Apple:
  script:
  - CONDA_ENVIRONMENT=.test-py3.yml
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
  - ". ./build-and-test-py-project-within-miniconda.sh"
  tags:
  - apple
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Pylint:
  script:
  - EXTRA_INSTALL="numpy sympy symengine scipy pexpect"
  - PY_EXE=python3
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-pylint.sh
  - ". ./prepare-and-run-pylint.sh pymbolic test/test_*.py"
  tags:
  - python3
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - linux
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh pymbolic test"
  tags:
  - python3
  except:
  - tags
