# CMake generated Testfile for 
# Source directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard
# Build directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(discardtest1_0000_0000 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/discardtest1_0000" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/0000.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(discardtest1_0000_0000 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;4;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;0;")
add_test(discardtest1_0001_0001 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/discardtest1_0001" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/0001.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(discardtest1_0001_0001 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;4;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;0;")
add_test(discardtest2_0000_0000 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/discardtest2_0000" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/0000.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(discardtest2_0000_0000 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;15;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;0;")
add_test(discardtest2_0001_0001 "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/discardtest2_0001" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-testtools/dune/testtools/test/cmakediscard/0001.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(discardtest2_0001_0001 PROPERTIES  LABELS "DUNE_SYSTEMTEST" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;324;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/cmake/modules/DuneSystemtests.cmake;398;add_system_test_per_target;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;15;dune_add_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-testtools/dune/testtools/test/cmakediscard/CMakeLists.txt;0;")
