# CMake generated Testfile for 
# Source directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic
# Build directory: /Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(lineartransport_numdiff_explicit "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_numdiff_explicit" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_numdiff_explicit.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(lineartransport_numdiff_explicit PROPERTIES  LABELS "" SKIP_RETURN_CODE "77" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/cmake/modules/GeneratedSystemtests.cmake;183;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;1;dune_add_formcompiler_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;0;")
add_test(lineartransport_numdiff_implicit "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_numdiff_implicit" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_numdiff_implicit.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(lineartransport_numdiff_implicit PROPERTIES  LABELS "" SKIP_RETURN_CODE "77" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/cmake/modules/GeneratedSystemtests.cmake;183;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;1;dune_add_formcompiler_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;0;")
add_test(lineartransport_symdiff_explicit "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_symdiff_explicit" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_symdiff_explicit.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(lineartransport_symdiff_explicit PROPERTIES  LABELS "" SKIP_RETURN_CODE "77" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/cmake/modules/GeneratedSystemtests.cmake;183;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;1;dune_add_formcompiler_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;0;")
add_test(lineartransport_symdiff_implicit "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_symdiff_implicit" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/lineartransport_symdiff_implicit.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(lineartransport_symdiff_implicit PROPERTIES  LABELS "" SKIP_RETURN_CODE "77" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/cmake/modules/GeneratedSystemtests.cmake;183;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;1;dune_add_formcompiler_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;0;")
add_test(linearacoustics "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/linearacoustics" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/linearacoustics.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(linearacoustics PROPERTIES  LABELS "" SKIP_RETURN_CODE "77" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/cmake/modules/GeneratedSystemtests.cmake;183;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;6;dune_add_formcompiler_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;0;")
add_test(shallowwater "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/run-in-dune-env" "dune_execute.py" "--exec" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/shallowwater" "--ini" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/release-build/dune-codegen/test/hyperbolic/shallowwater.ini" "--source" "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic" "--mpi-exec" "/opt/homebrew/bin/mpiexec" "--mpi-numprocflag=-n" "--mpi-preflags" "" "--mpi-postflags" "" "--max-processors=2")
set_tests_properties(shallowwater PROPERTIES  LABELS "quick" SKIP_RETURN_CODE "77" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/cmake/modules/GeneratedSystemtests.cmake;183;_add_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;11;dune_add_formcompiler_system_test;/Users/wjq/Documents/Github-CI/deal.II-mini/temp/iwr-course-2021/dune/dune-codegen/test/hyperbolic/CMakeLists.txt;0;")
